<a href="https://colab.research.google.com/github/stereoxyz/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**is a numerical Python. we can use it to store all sorts of data in one dimensional array, two dimensional array and n-dimensional arrays. we use numpy instead of list because numpy take less space which is easy to read fast. and it takes contigious space and numpy store same datatype so we dont need to check the data type of each elements when we are iterating through the iteraor.

In [ ]:
#initalize of an array
import numpy as np
a=np.array([2,4,6,8])#one dimensional aray
print(a)

[2 4 6 8]


In [ ]:
#get size
a.size

4

In [ ]:
#get shape
a.shape

(4,)

In [ ]:
#creation of 2D array
a=np.array([[2,4,6,8], [4,3,28,4]])
a.dtype
a.itemsize

8

Accessing a specific elemts with the help of Slicing / indexing:
In numpy we can get a specific elements and specific columns and rows with the help of slicing/indexing.
slicing of aray : [rows, column]

In [18]:
a=np.array([[[2,4,6,8], [10,5,7,9],[13,16,17,18],[44,55,77,88]]])
#if i want to get 17
print(a[0,2,2])
#for row and columns
print(a[0,:,3]) #for last column
print(a[0,1,:]) # returns second row

17
[ 8  9 18 88]
[10  5  7  9]


**creation of differents array**




In [22]:
#array with all zeros
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
#array with all ones
a=np.ones((3,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [26]:
#creation of identity matrix
np.identity(4) #we only pass one parameter because identity matrix is always square


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**usage of numpy in mathematics**: we can do all kinds of arithmatics operations with the help of numpy. we can do with two or different arays together or we can add manually a differnt numbers in our array

In [27]:
a=np.array([2,4,6])
print(a+2)#added 2 in every elements

[4 6 8]


In [28]:
#for multiple arrays:
a=np.array([2,4,6])
b=np.array([4,6,7])
print(a*b)

[ 8 24 42]


In [35]:
#multiplication of the matrixes
a=np.array([[4,5,6,8],[8,9,5,6]])
b=np.array([[8,6,7,5],[9,8,9,5]])
b=b.T #Transpose of matrix (means changage of rows and columns.)
print(np.linalg.matmul(a,b))

[[144 170]
 [183 219]]


**Random Number Generation**

In [36]:
a=np.random.rand(2,3)
print(a) # returns the random float int between 0 and 1

[[0.00084059 0.55310343 0.17421979]
 [0.66162929 0.1470799  0.19707355]]


In [38]:
a=np.random.randint(20,size=(2,3,4)) #we pass two parameter one is the range and another is the size of our array
print(a)

[[[17  8 15 15]
  [ 1  6  3  3]
  [ 3 18 16  9]]

 [[ 9  6 12  8]
  [ 2  1  3  2]
  [ 6  0  4 12]]]


In [39]:
a=np.arange(20)#returns the array with the int between 0 to 19
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [46]:
a=np.linspace(0,20,5) #create evenly spaced numbers between two values.
print(a)

[ 0.  5. 10. 15. 20.]


**Concatenate of 2 arrays**

In [59]:
a=np.array([2,3,5,6,7])
b=np.array([4,8,9,10,11])
np.concatenate((a,b))

array([ 2,  3,  5,  6,  7,  4,  8,  9, 10, 11])

In [61]:
np.std((a,b))#returns standard deviation

np.float64(2.8722813232690143)

**Reshaping of an array** : we can change the shape of our array with the help of .reshape function . for that we need to have the same numbers of elements of the new array and our original aray.

In [67]:
a=np.array([98,99,34,56,78,45,67,78])
a.reshape(2,2,2)#This is valid for reshaping
a.reshape(3,2)#This is invalid because the numbers of elemnts will be differents here


array([[[98, 99],
        [34, 56]],

       [[78, 45],
        [67, 78]]])

**Linear Algebra Basis With Numpy** : we can solve multiple linear algerbra problems with the help of numpy like inverse of the matrix, determinant of the matrix, multiplication fo the matrix.

In [70]:
a=np.identity(4)
np.linalg.det(a) #return the determinent of the matrix

np.float64(1.0)

In [74]:
a=np.array([[4,5],[7,8]])
np.linalg.inv(a) #returns the inverse of the matrix

array([[-2.66666667,  1.66666667],
       [ 2.33333333, -1.33333333]])

**Some Important Functions**

In [78]:
#sum
a=np.array([[2,4,6],[6,7,8],[4,32,1]])
np.sum(a)#returns the total sum of an array
np.sum(a, axis=0)#returns the sum of the column
np.sum(a, axis=1)#returns the sum of the rows

array([12, 21, 37])

In [82]:
#min
np.min(a)
np.max(a)
np.argmax(a)#returns the index of the maximum element
np.argmin(a)#returns the index of the smallest element

np.int64(8)

**How to load a data from file in Numpy**
we can load a data from numpy with the help fo the function

In [ ]:
data=np.genfromtxt("file path", delimiter=',')