<a href="https://colab.research.google.com/github/stereoxyz/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a numerical Python. we can use it to store all sorts of data in one dimensional array, two dimensional array and n-dimensional arrays. we use numpy instead of list because numpy take less space which is easy to read fast. and it takes contigious space and numpy store same datatype so we dont need to check the data type of each elements when we are iterating through the iteraor.

In [ ]:
#initalize of an array
import numpy as np
a=np.array([2,4,6,8])#one dimensional aray
print(a)

[2 4 6 8]


In [ ]:
#get size
a.size

4

In [ ]:
#get shape
a.shape

(4,)

In [ ]:
#creation of 2D array
a=np.array([[2,4,6,8], [4,3,28,4]])
a.dtype
a.itemsize

8

Accessing a specific elemts with the help of Slicing / indexing:
In numpy we can get a specific elements and specific columns and rows with the help of slicing/indexing.
slicing of aray : [rows, column]

In [18]:
a=np.array([[[2,4,6,8], [10,5,7,9],[13,16,17,18],[44,55,77,88]]])
#if i want to get 17
print(a[0,2,2])
#for row and columns
print(a[0,:,3]) #for last column
print(a[0,1,:]) # returns second row

17
[ 8  9 18 88]
[10  5  7  9]
